#!/usr/bin/env python3
"""
Fact of the Day Status Line Plugin for Claude Code
Displays random facts while Claude is thinking
"""

import json
import sys
import random
import time

# Facts organized by category with emojis (50 facts per category)
FACTS = {
    "💡": [  # General/Mixed facts
        "Honey never spoils. Archaeologists found 3000-year-old honey in Egyptian tombs that was still edible.",
        "Octopuses have three hearts and blue blood.",
        "A day on Venus is longer than a year on Venus.",
        "Bananas are berries, but strawberries aren't.",
        "The shortest war in history lasted 38-45 minutes (Britain vs Zanzibar, 1896).",
        "Sharks existed before trees.",
        "A group of flamingos is called a 'flamboyance'.",
        "The inventor of the Pringles can is buried in one.",
        "Wombat poop is cube-shaped.",
        "Scotland's national animal is the unicorn.",
        "There are more possible chess games than atoms in the observable universe.",
        "The first computer programmer was Ada Lovelace in the 1840s.",
        "A jiffy is an actual unit of time: 1/100th of a second.",
        "The moon has moonquakes.",
        "Hot water freezes faster than cold water (Mpemba effect).",
        "Cows have best friends and get stressed when separated.",
        "The Hawaiian alphabet has only 12 letters.",
        "A cloud can weigh more than a million pounds.",
        "Humans share 60% of their DNA with bananas.",
        "The longest hiccuping spree lasted 68 years.",
        "Dolphins sleep with one eye open.",
        "The Eiffel Tower can grow 6 inches taller in summer.",
        "A bolt of lightning is 5x hotter than the sun's surface.",
        "Sloths can hold their breath longer than dolphins.",
        "The inventor of the frisbee was turned into a frisbee after death.",
        "Polar bear fur is transparent, not white.",
        "The first oranges weren't orange - they were green.",
        "A cockroach can live for weeks without its head.",
        "Glass balls can bounce higher than rubber ones.",
        "The longest English word is 189,819 letters long (a protein name).",
        "Butterflies taste with their feet.",
        "The code name for the iPhone was 'Purple'.",
        "The first computer virus was created in 1983.",
        "Git was created by Linus Torvalds in just 10 days.",
        "The first website is still online at info.cern.ch.",
        "Python was named after Monty Python, not the snake.",
        "The @ symbol is called 'snabel-a' (elephant trunk) in Danish.",
        "The first computer mouse was made of wood.",
        "NASA still uses code from the 1970s on Voyager.",
        "The average coder writes about 10 lines of finished code per day.",
        "An octopus has nine brains - one central and one in each arm.",
        "The world's oldest known joke is a Sumerian fart joke from 1900 BC.",
        "A sneeze travels at about 100 miles per hour.",
        "The fingerprints of koalas are virtually indistinguishable from humans.",
        "The inventor of the pacemaker accidentally invented it while building something else.",
        "There are more trees on Earth than stars in the Milky Way.",
        "A group of porcupines is called a prickle.",
        "The longest recorded flight of a chicken is 13 seconds.",
        "The electric chair was invented by a dentist.",
        "Oxford University predates the Mayan civilization.",
    ],
    "🚀": [  # Space & Science
        "Neutron stars are so dense that a teaspoon would weigh 6 billion tons.",
        "There's a planet made of diamonds twice the size of Earth (55 Cancri e).",
        "One million Earths could fit inside the Sun.",
        "Space is completely silent - there's no medium to carry sound.",
        "A photon takes 40,000 years to travel from the Sun's core to its surface.",
        "The footprints on the Moon will last for 100 million years.",
        "Saturn would float if you could find a bathtub big enough.",
        "There are more stars in the universe than grains of sand on Earth.",
        "The Voyager 1 spacecraft is the farthest human-made object from Earth.",
        "Black holes can sing - they emit sound waves in B-flat.",
        "Water can boil and freeze at the same time (triple point).",
        "There are about 8.7 million species on Earth, and 86% are undiscovered.",
        "The Sun makes up 99.86% of all mass in our solar system.",
        "If you could fold a piece of paper 42 times, it would reach the Moon.",
        "The observable universe is 93 billion light-years in diameter.",
        "A year on Pluto is 248 Earth years long.",
        "Jupiter's Great Red Spot is shrinking - it used to fit 3 Earths, now only 1.",
        "The Milky Way and Andromeda galaxies will collide in 4.5 billion years.",
        "There are more molecules in a glass of water than glasses of water in all oceans.",
        "The largest known star, UY Scuti, could fit 5 billion Suns inside it.",
        "Astronauts grow up to 2 inches taller in space due to spine decompression.",
        "The International Space Station travels at 17,500 mph.",
        "Mars has the largest volcano in the solar system - Olympus Mons.",
        "Light from the Sun takes 8 minutes and 20 seconds to reach Earth.",
        "There may be 2 trillion galaxies in the observable universe.",
        "The cosmic microwave background is the oldest light in the universe.",
        "A black hole the mass of Earth would be the size of a marble.",
        "The Moon is slowly drifting away from Earth at 1.5 inches per year.",
        "Enceladus, Saturn's moon, has geysers that shoot water into space.",
        "The hottest planet isn't the closest to the Sun - it's Venus.",
        "Io, Jupiter's moon, has over 400 active volcanoes.",
        "The Sun loses 4 million tons of mass every second.",
        "There are rogue planets wandering through space without a star.",
        "Einstein's brain was preserved and studied after his death.",
        "Quantum entanglement allows particles to affect each other instantly across any distance.",
        "The speed of light is 299,792,458 meters per second exactly.",
        "Antimatter is the most expensive substance - $62.5 trillion per gram.",
        "Time passes faster on GPS satellites than on Earth due to relativity.",
        "The Hubble Space Telescope can see galaxies 13.4 billion light-years away.",
        "A pulsar rotates up to 716 times per second.",
        "The largest known structure is the Hercules-Corona Borealis Great Wall.",
        "Dark matter makes up about 27% of the universe.",
        "The Kuiper Belt contains over a trillion comets.",
        "The closest star to our Sun is Proxima Centauri at 4.24 light-years.",
        "Saturn's moon Titan has liquid methane lakes.",
        "The event horizon of a black hole is the point of no return.",
        "Gravitational waves were first detected in 2015.",
        "The James Webb Space Telescope is 100x more powerful than Hubble.",
        "A magnetar's magnetic field is a quadrillion times stronger than Earth's.",
        "The universe is expanding faster than the speed of light.",
    ],
    "🐾": [  # Animals
        "A shrimp's heart is located in its head.",
        "Elephants are the only animals that can't jump.",
        "A snail can sleep for three years.",
        "Kangaroos can't walk backwards.",
        "Hummingbirds are the only birds that can fly backwards.",
        "Horses and cows sleep standing up.",
        "A crocodile cannot stick out its tongue.",
        "Starfish don't have brains.",
        "Koalas sleep up to 22 hours a day.",
        "A giraffe's tongue is about 21 inches long.",
        "Bees can recognize human faces.",
        "Sea otters hold hands while sleeping to keep from drifting apart.",
        "Crows can remember human faces and hold grudges.",
        "Axolotls can regenerate their brains.",
        "Tardigrades can survive in the vacuum of space.",
        "The heart of a blue whale is so big, a small child could crawl through its arteries.",
        "Mantis shrimp can punch at 50 mph, fast enough to boil water around their fist.",
        "Cats have over 20 vocalizations, including the meow, purr, and chirp.",
        "A group of owls is called a parliament.",
        "Squirrels plant thousands of trees each year by forgetting where they buried nuts.",
        "Octopuses can taste with their entire body.",
        "Flamingos can only eat with their heads upside down.",
        "A group of hedgehogs is called a prickle.",
        "Dolphins have names for each other and call out to specific individuals.",
        "The pistol shrimp is the loudest animal in the ocean.",
        "Penguins propose to their mates with pebbles.",
        "A chameleon's tongue is twice the length of its body.",
        "Honey badgers can withstand bee stings, porcupine quills, and snake venom.",
        "Sloths can take up to a month to digest a single leaf.",
        "The immortal jellyfish can revert to its juvenile form indefinitely.",
        "An ant can lift 50 times its own body weight.",
        "Spiders can't fly, but some 'balloon' on silk threads for miles.",
        "A group of ravens is called an unkindness.",
        "Wolves can eat 20 pounds of meat in a single sitting.",
        "The mimic octopus can imitate 15 different species.",
        "Naked mole rats are immune to cancer.",
        "A blue whale's tongue weighs as much as an elephant.",
        "Cuttlefish have three hearts and green-blue blood.",
        "Elephants mourn their dead and have funeral rituals.",
        "A woodpecker's tongue wraps around its skull.",
        "The box jellyfish has 24 eyes.",
        "Goats have rectangular pupils for panoramic vision.",
        "Platypuses don't have stomachs.",
        "A blue-ringed octopus carries enough venom to kill 26 adults.",
        "Electric eels can produce 860 volts of electricity.",
        "Hippos produce pink milk.",
        "A group of cats is called a clowder.",
        "Orcas are natural predators of moose.",
        "Wombats are the only animals whose poop is cube-shaped.",
        "A flea can jump 150 times its body length.",
    ],
    "💻": [  # Technology & Computing
        "The first 1GB hard drive (1980) weighed 550 pounds and cost $40,000.",
        "There are about 500 million tweets sent every day.",
        "The QWERTY keyboard was designed to slow typists down.",
        "The first domain ever registered was symbolics.com in 1985.",
        "Email existed before the World Wide Web.",
        "The first computer bug was an actual bug - a moth in a Harvard computer (1947).",
        "The average smartphone has more computing power than NASA had in 1969.",
        "There are over 2 billion websites, but 90% are inactive.",
        "The first YouTube video was uploaded on April 23, 2005.",
        "Over 300 hours of video are uploaded to YouTube every minute.",
        "The first text message was sent in 1992 and said 'Merry Christmas'.",
        "The first webcam was used to monitor a coffee pot at Cambridge University.",
        "JavaScript was created in just 10 days.",
        "The Linux kernel has over 27 million lines of code.",
        "The first computer game was created in 1962 - Spacewar!",
        "A single Google search uses more computing power than the entire Apollo mission.",
        "Amazon was originally called Cadabra.",
        "Apple's first logo featured Isaac Newton sitting under an apple tree.",
        "The Firefox logo isn't a fox - it's a red panda.",
        "The first iPhone didn't have copy and paste functionality.",
        "The first hard drive had a capacity of 5MB.",
        "Wi-Fi doesn't stand for 'Wireless Fidelity' - it's just a trademark name.",
        "The first spam email was sent in 1978 to 400 users on ARPANET.",
        "The @ symbol was chosen for email because it was the least used key.",
        "The floppy disk save icon is still used despite floppies being obsolete.",
        "Bill Gates' house was designed using a Macintosh computer.",
        "The first webcam image was of a coffee pot at Cambridge University.",
        "Over 6,000 new computer viruses are created every month.",
        "Sony's first product was a rice cooker.",
        "The first computer programmer was Ada Lovelace in 1843.",
        "The Apollo 11 computer had less power than a modern calculator.",
        "CAPTCHA stands for 'Completely Automated Public Turing test'.",
        "The first website went live on August 6, 1991.",
        "Google's name is a misspelling of 'googol' (10^100).",
        "The first banner ad appeared in 1994 with a 44% click rate.",
        "IBM's Watson beat Jeopardy champions in 2011.",
        "The average person unlocks their phone 150 times per day.",
        "The first VCR was the size of a piano.",
        "Bluetooth is named after a 10th-century Danish king.",
        "The first electronic computer ENIAC weighed 27 tons.",
        "Russia built a computer that ran on water in 1936.",
        "The first Apple computer sold for $666.66.",
        "There are more than 700 programming languages.",
        "The first mouse was invented in 1964 and was made of wood.",
        "The term 'bug' was popularized by Grace Hopper after finding a moth.",
        "The world's first camera took 8 hours to capture a single photo.",
        "USB was invented in 1996 by Ajay Bhatt at Intel.",
        "The first emoji was created in Japan in 1999.",
        "The Nintendo Game Boy outsold every other console in the 1990s.",
        "95% of all SMS messages are read within 3 minutes of being sent.",
    ],
    "📜": [  # History
        "Cleopatra lived closer in time to the Moon landing than to the building of the pyramids.",
        "Oxford University is older than the Aztec Empire.",
        "The Great Wall of China is not visible from space with the naked eye.",
        "Vikings used to give kittens to new brides as essential household gifts.",
        "Ancient Romans used crushed mouse brains as toothpaste.",
        "Napoleon was once attacked by a horde of rabbits.",
        "In 1932, Australia lost a war against emus (The Great Emu War).",
        "The shortest reign of a king was just 20 minutes (Louis XIX of France).",
        "Albert Einstein was offered the presidency of Israel in 1952. He declined.",
        "The inventor of the treadmill created it as a prison torture device.",
        "Ancient Egyptians used slabs of stone as pillows.",
        "The Leaning Tower of Pisa took 200 years to build and started tilting immediately.",
        "The longest war in history lasted 335 years with no casualties (Netherlands vs Isles of Scilly).",
        "Genghis Khan killed so many people that it cooled the Earth's climate.",
        "Abraham Lincoln was a champion wrestler and lost only 1 of 300 matches.",
        "In ancient Greece, throwing an apple at someone was a marriage proposal.",
        "The Roman Emperor Caligula made his horse a senator.",
        "Cleopatra was Greek, not Egyptian.",
        "The Great Pyramid was the tallest structure for 3,800 years.",
        "Vikings never wore horned helmets - that's a 19th-century myth.",
        "The first recorded use of 'OMG' was in a letter to Winston Churchill in 1917.",
        "Ancient Egyptians shaved their eyebrows to mourn their cats.",
        "Benjamin Franklin wanted the turkey as the national bird, not the eagle.",
        "The shortest woman in history was Pauline Musters at 23 inches tall.",
        "The Aztecs sacrificed 1% of their population every year.",
        "Roman gladiators rarely fought to the death - they were too expensive.",
        "The Great Fire of London destroyed 13,200 houses but only killed 6 people.",
        "Queen Victoria survived 8 assassination attempts.",
        "The first Olympics in 1896 had only 43 events.",
        "Tutankhamun's tomb curse killed zero archaeologists.",
        "The Titanic's musicians played for 2+ hours as the ship sank.",
        "Ancient Rome had shopping malls with 150+ shops.",
        "George Washington's teeth were not wooden - they were hippopotamus ivory.",
        "The Spanish flu didn't originate in Spain.",
        "The first vending machine was invented in ancient Egypt for holy water.",
        "Cleopatra had a perfume factory.",
        "The oldest known recipe is for beer - 4,000 years old from Sumeria.",
        "Napoleon wasn't short - he was 5'7\", average for his time.",
        "The first written record of a joke is from 1900 BC in Sumeria.",
        "Ancient Greeks exercised naked - 'gymnasium' comes from 'gymnos' (naked).",
        "The Colosseum could be flooded for naval battle reenactments.",
        "Harriet Tubman also served as a spy and scout during the Civil War.",
        "The Library of Alexandria was destroyed over centuries, not in one fire.",
        "Thomas Edison didn't invent the light bulb - he improved it.",
        "The first Olympics included poetry and art competitions.",
        "Pirates wore eye patches to see better in the dark below deck.",
        "The last guillotine execution in France was in 1977.",
        "The Code of Hammurabi is one of the oldest written laws (1754 BC).",
        "Toilet paper was invented in China in the 6th century AD.",
        "The first written peace treaty was between Egypt and the Hittites in 1259 BC.",
    ],
    "🤖": [  # Artificial Intelligence
        "The term 'Artificial Intelligence' was coined by John McCarthy in 1956.",
        "The first AI program, Logic Theorist, was created in 1956.",
        "GPT-3 has 175 billion parameters - GPT-4 is rumored to have over 1 trillion.",
        "The Turing Test was proposed by Alan Turing in 1950.",
        "Deep Blue beat chess champion Garry Kasparov in 1997.",
        "AlphaGo defeated world Go champion Lee Sedol in 2016 - a decade earlier than predicted.",
        "The first chatbot, ELIZA, was created in 1966 at MIT.",
        "Neural networks were first proposed in 1943 by McCulloch and Pitts.",
        "AI can now generate realistic human faces of people who don't exist.",
        "The word 'robot' comes from the Czech word 'robota' meaning forced labor.",
        "OpenAI was founded in 2015 with a $1 billion pledge.",
        "Anthropic was founded in 2021 by former OpenAI researchers.",
        "Claude is named after Claude Shannon, the father of information theory.",
        "The ImageNet competition accelerated deep learning breakthroughs in 2012.",
        "AI systems can now write code, compose music, and create art.",
        "Transformers, the architecture behind modern LLMs, was introduced by Google in 2017.",
        "The 'AI winter' refers to periods of reduced funding and interest in AI research.",
        "DALL-E gets its name from Salvador Dali and WALL-E.",
        "Reinforcement learning taught AI to play Atari games better than humans.",
        "The first self-driving car demo was in 1986 by Carnegie Mellon's Navlab.",
        "AlphaFold solved the protein folding problem in 2020.",
        "GPT stands for Generative Pre-trained Transformer.",
        "The Attention mechanism revolutionized NLP in the 'Attention Is All You Need' paper.",
        "AI can now detect cancer in medical images more accurately than doctors.",
        "The perceptron, an early neural network, was invented in 1958.",
        "AI-generated art won a state fair competition in 2022.",
        "The Dartmouth Conference of 1956 is considered the birth of AI.",
        "Sophia the Robot became the first robot to receive citizenship (Saudi Arabia).",
        "GPT-4 passed the bar exam in the 90th percentile.",
        "The NVIDIA GPU boom was driven by AI training demands.",
        "AlphaZero mastered chess, shogi, and Go from scratch in 24 hours.",
        "Generative AI market is projected to reach $1.3 trillion by 2032.",
        "The first neural network to recognize handwritten digits was LeNet in 1989.",
        "BERT revolutionized search engines in 2018.",
        "AI assistants process over 1 billion queries daily worldwide.",
        "The backpropagation algorithm dates back to 1986.",
        "Stable Diffusion made AI art generation accessible to everyone in 2022.",
        "ChatGPT reached 100 million users in 2 months - the fastest growing app ever.",
        "The 'Paperclip Maximizer' is a thought experiment about AI alignment risks.",
        "LLMs don't truly understand - they predict the next token probabilistically.",
        "Mixture of Experts (MoE) architectures reduce AI compute costs.",
        "The Chinese Room argument challenges whether AI can truly understand.",
        "Constitutional AI is a method for training safer AI systems.",
        "AI hallucinations occur when models generate false but plausible information.",
        "The first image generated by AI was in 1973 by Harold Cohen's AARON.",
        "Multimodal AI can process text, images, audio, and video together.",
        "The Elo rating of top chess AI exceeds 3500 - far beyond any human.",
        "Retrieval-Augmented Generation (RAG) helps AI cite sources.",
        "AI chips process trillions of operations per second.",
        "The EU AI Act is the first major AI regulation in the world.",
    ],
    "🌉": [  # San Francisco
        "The Golden Gate Bridge's orange color is called 'International Orange'.",
        "San Francisco's cable cars are the only mobile National Historic Landmark.",
        "Alcatraz was a military fort before becoming a federal prison.",
        "The 1906 SF earthquake and fire destroyed 80% of the city.",
        "San Francisco has more dogs than children.",
        "The fortune cookie was invented in San Francisco, not China.",
        "Lombard Street isn't actually the most crooked street in SF - Vermont Street is.",
        "The SF fog has a name: Karl. It even has a Twitter account.",
        "Levi Strauss invented blue jeans in San Francisco during the Gold Rush.",
        "The Summer of Love in 1967 drew 100,000 hippies to the Haight-Ashbury.",
        "Twitter, Uber, Airbnb, and Salesforce were all founded in San Francisco.",
        "The Transamerica Pyramid was the tallest building in SF for 45 years.",
        "San Francisco is built on over 50 hills.",
        "The Bay Area has more Michelin-starred restaurants than any other US metro.",
        "Anchor Steam Beer is the oldest craft brewery in America, founded in SF in 1896.",
        "The first Internet message was sent from UCLA to Stanford in 1969.",
        "Ghirardelli is the longest continuously operating chocolate company in the US.",
        "The SF Giants mascot, Lou Seal, has been around since 1996.",
        "Coit Tower was built with a $118,000 bequest from Lillie Hitchcock Coit.",
        "The Painted Ladies are a row of Victorian houses, not a specific house.",
        "The Golden Gate Bridge took 4 years to build and cost $35 million.",
        "San Francisco's official city song is 'I Left My Heart in San Francisco'.",
        "The city has over 3,000 Victorian and Edwardian homes.",
        "BART opened in 1972 as the first heavy rail system in the US since 1907.",
        "The Palace of Fine Arts was built for the 1915 Panama-Pacific Exposition.",
        "Emperor Norton was San Francisco's beloved self-proclaimed Emperor in the 1800s.",
        "The Sutro Baths could hold 10,000 swimmers at once.",
        "Fisherman's Wharf was historically home to Italian immigrant fishermen.",
        "The Castro became the first openly gay neighborhood in the US in the 1970s.",
        "The Bay Bridge is actually two bridges connected at Yerba Buena Island.",
        "San Francisco's Chinatown is the oldest in North America (established 1848).",
        "The city banned plastic bags in 2007 - the first US city to do so.",
        "Golden Gate Park is larger than Central Park.",
        "The Fairmont Hotel survived the 1906 earthquake and opened a year later.",
        "Sourdough bread became an SF staple during the Gold Rush.",
        "The St. Francis Hotel has hosted every US president since Taft.",
        "Dashiell Hammett wrote 'The Maltese Falcon' while living in SF.",
        "The first jukebox debuted at the Palais Royale Saloon in SF in 1889.",
        "Oracle Park is built on landfill over the site of an old shipyard.",
        "The Exploratorium was founded by Frank Oppenheimer, brother of Robert.",
        "The Ferry Building has operated continuously since 1898.",
        "San Francisco was originally called Yerba Buena (good herb).",
        "The Japanese Tea Garden in Golden Gate Park is the oldest in the US.",
        "The city has an average of 260 sunny days per year.",
        "Dolores Park was a Jewish cemetery until 1894.",
        "The Sea Lions arrived at Pier 39 after the 1989 earthquake.",
        "Twin Peaks was the first live-action American TV show filmed entirely in SF.",
        "The SF Mint survived the 1906 earthquake and saved $200 million in gold.",
        "Hippie Hill in Golden Gate Park hosts annual 4/20 gatherings.",
        "The Grateful Dead house at 710 Ashbury is a famous landmark.",
    ],
    "🧗": [  # Rock Climbing
        "Free solo climbing means climbing without any ropes or protective gear.",
        "Alex Honnold free soloed El Capitan (3,000 ft) in 3 hours 56 minutes.",
        "The first ascent of El Capitan took 47 days in 1958.",
        "Tommy Caldwell and Kevin Jorgeson spent 19 days on the Dawn Wall.",
        "Indoor climbing was added to the Olympics in Tokyo 2020.",
        "Climbing shoes are designed to be painfully tight for better grip.",
        "Chalk is used to keep hands dry and improve grip on holds.",
        "The Yosemite Decimal System rates climbs from 5.0 to 5.15.",
        "A 'dyno' is a dynamic move where all limbs leave the wall.",
        "Bouldering problems are typically under 20 feet high.",
        "The first climbing gym opened in Seattle in 1987.",
        "Lynn Hill was the first person to free climb The Nose on El Capitan in 1993.",
        "A 'send' means successfully completing a climbing route.",
        "Hangboards are used to train finger strength for climbing.",
        "The Hueco Tanks in Texas is famous for world-class bouldering.",
        "Adam Ondra is considered one of the greatest climbers of all time.",
        "Crack climbing involves jamming hands and feet into rock cracks.",
        "A 'whipper' is a long, dramatic fall while lead climbing.",
        "Climbing tape protects skin from cuts and improves grip.",
        "The 'pink point' style means climbing with pre-placed gear.",
        "V-scale (Vermin scale) rates bouldering problems from V0 to V17.",
        "The first 5.15d route was 'Silence' by Adam Ondra in 2017.",
        "Speed climbing world records are under 5 seconds for a 15m wall.",
        "Trad climbing involves placing your own protective gear.",
        "The 'crux' is the hardest section of a climbing route.",
        "Crimps are small holds gripped with bent fingers.",
        "Moonboard and Kilter are popular standardized training boards.",
        "Campus boards were invented by Wolfgang Güllich in 1988.",
        "A 'flash' means completing a route on the first try with beta.",
        "Red point means completing a route after previous attempts.",
        "Slab climbing involves low-angle faces requiring balance and friction.",
        "The first artificial climbing wall was built in the UK in 1964.",
        "Climbing has its own grading systems: French, UIAA, British, and more.",
        "Dave Graham established 'The Story of Two Worlds' (V16) in 2005.",
        "Professional climbers train finger strength obsessively.",
        "The Dawn Wall on El Capitan has pitches rated up to 5.14d.",
        "Janja Garnbret is considered the greatest competition climber ever.",
        "Deep water soloing involves climbing over water without ropes.",
        "The first women's 5.15a was climbed by Margo Hayes in 2017.",
        "Carabiners used in climbing can hold over 20 kN (4,500 lbs).",
        "Prusik knots allow climbers to ascend ropes.",
        "A 'beta spray' is when someone gives unsolicited climbing advice.",
        "The Fontainebleau forest in France is a legendary bouldering destination.",
        "Climbing gyms have grown 10x in the US since 2010.",
        "A 'project' is a route you're working on over multiple sessions.",
        "Ondra's 'Silence' took over 50 days of attempts to complete.",
        "Climbers often develop asymmetrical finger strength.",
        "The 'no hands rest' involves using features to rest without hands.",
        "Climbing burns 500-900 calories per hour.",
        "The phrase 'take' means ask your belayer to hold the rope tight.",
    ],
    "🍎": [  # Food & Drink
        "Cucumbers are 96% water.",
        "Apples float because they are 25% air.",
        "Peanuts are one of the ingredients in dynamite.",
        "Lemons contain more sugar than strawberries.",
        "Crackers are worse for your teeth than candy.",
        "Almonds are members of the peach family.",
        "Carrots were originally purple, not orange.",
        "Ketchup was sold as medicine in the 1830s.",
        "Avocados are toxic to birds.",
        "Fortune cookies were invented in San Francisco, not China.",
        "Honey is the only food that never spoils.",
        "The most expensive coffee is made from civet cat droppings.",
        "Bananas are radioactive due to potassium-40.",
        "Chocolate was once used as currency by the Aztecs.",
        "Nutmeg can be hallucinogenic in large quantities.",
        "Worcestershire sauce is made from fermented anchovies.",
        "Saffron is the most expensive spice in the world.",
        "Cashews grow on the bottom of cashew apples.",
        "Popsicles were invented by an 11-year-old boy.",
        "Cheese is the most shoplifted food in the world.",
        "Strawberries have more vitamin C than oranges.",
        "Potatoes were the first vegetable grown in space.",
        "Corn is a grass, not a vegetable.",
        "The oldest wine ever found is over 8,000 years old.",
        "McDonald's sells 75 burgers per second worldwide.",
        "Airplane food tastes bland because altitude dulls taste buds.",
        "The first food eaten in space was apple sauce.",
        "Spam is short for 'Spiced Ham'.",
        "The world's most expensive pizza costs $12,000.",
        "Bubble tea was invented in Taiwan in the 1980s.",
        "Pineapples take 2-3 years to grow to full size.",
        "The fear of cooking is called mageirocophobia.",
        "Coconuts kill more people than sharks each year.",
        "Arachibutyrophobia is the fear of peanut butter sticking to the roof of your mouth.",
        "Expiration dates on water bottles are for the bottle, not the water.",
        "The world record for eating hot dogs is 76 in 10 minutes.",
        "Ripe cranberries bounce like rubber balls.",
        "Coffee is the second most traded commodity after oil.",
        "The sandwich was named after the Earl of Sandwich.",
        "Cabbage is 91% water.",
        "One baguette is sold every second in France.",
        "The oldest restaurant in the world opened in Madrid in 1725.",
        "SPAM has its own museum in Minnesota.",
        "Champagne was invented by accident.",
        "One fast food meal can contain a week's worth of sodium.",
        "Astronauts can't burp in space due to lack of gravity.",
        "The average American eats 35 tons of food in a lifetime.",
        "Ranch dressing was invented on an actual ranch in Alaska.",
        "The world's largest omelette used 145,000 eggs.",
        "Cilantro tastes like soap to 10% of people due to genetics.",
    ],
    "🌍": [  # Geography & Nature
        "Russia spans 11 time zones.",
        "Canada has more lakes than the rest of the world combined.",
        "Australia is wider than the Moon.",
        "There's a town in Norway called Hell, and it freezes over every winter.",
        "The Amazon rainforest produces 20% of the world's oxygen.",
        "Mount Everest grows about 4mm every year.",
        "90% of the world's fresh water is in Antarctica.",
        "The Dead Sea is so salty you can float effortlessly on its surface.",
        "Rainbows are actually full circles - we only see arcs from the ground.",
        "A single lightning bolt can heat the air to 30,000 Kelvin (5x the Sun's surface).",
        "The Sahara Desert was once a lush, green savanna.",
        "Lake Baikal contains 20% of the world's unfrozen fresh water.",
        "The Pacific Ocean is larger than all landmasses combined.",
        "Mount Chimborazo in Ecuador is the farthest point from Earth's center.",
        "There are more trees on Earth than stars in the Milky Way.",
        "The Amazon River has no bridges.",
        "Africa is the only continent in all four hemispheres.",
        "The Mariana Trench is deeper than Mount Everest is tall.",
        "Only 5% of the ocean has been explored.",
        "A hurricane releases energy equivalent to 10,000 nuclear bombs.",
        "Greenland is the largest island, but Australia is a continent.",
        "The highest waterfall is Angel Falls in Venezuela at 3,212 feet.",
        "The Bermuda Triangle has the same rate of accidents as any other region.",
        "Iceland grows 2 centimeters wider every year due to tectonic activity.",
        "The Great Barrier Reef is visible from space.",
        "There are underground rivers in the Amazon that mirror the river above.",
        "The Nile is the longest river, but the Amazon carries the most water.",
        "The oldest rocks on Earth are 4 billion years old.",
        "Trees communicate through underground fungal networks.",
        "Glaciers store about 69% of the world's fresh water.",
        "The tallest tree is Hyperion, a coast redwood at 380 feet.",
        "A single oak tree can absorb 48 pounds of CO2 per year.",
        "Antarctica is the only continent with no permanent population.",
        "The largest desert is actually Antarctica, not the Sahara.",
        "The Eye of the Sahara is a 30-mile wide rock formation.",
        "Sunflowers follow the sun across the sky (heliotropism).",
        "Bamboo can grow up to 35 inches in a single day.",
        "The oldest living tree is over 5,000 years old (Methuselah).",
        "Quicksand is rarely more than a few feet deep.",
        "The Earth's core is as hot as the surface of the Sun.",
        "Bioluminescent bays glow blue due to dinoflagellates.",
        "The Sargasso Sea is the only sea with no coastline.",
        "Coral reefs support 25% of all marine species.",
        "The Grand Canyon is over 1.8 billion years old at its base.",
        "Volcanoes can create lightning in their ash clouds.",
        "The Danakil Depression is the hottest place on Earth.",
        "Icebergs can be green, blue, or even striped.",
        "The longest cave system is Mammoth Cave at 400+ miles.",
        "The Northern Lights are caused by solar particles hitting atmosphere.",
        "Earthquakes can make the day shorter by redistributing Earth's mass.",
    ],
    "🎲": [  # Random Fun Facts
        "A 'moment' is a medieval unit of time equal to 90 seconds.",
        "The world's oldest known 'your mom' joke is 3,500 years old (Babylonian).",
        "There's a species of jellyfish that is biologically immortal.",
        "The inventor of the microwave only received $2 for his discovery.",
        "A day on Mercury lasts 59 Earth days.",
        "The Twitter bird's official name is Larry.",
        "There are more fake flamingos in the world than real ones.",
        "A group of pandas is called an 'embarrassment'.",
        "The shortest complete sentence in English is 'I am.'",
        "Venus is the only planet that spins clockwise.",
        "A blue whale's tongue weighs as much as an elephant.",
        "More people are killed by coconuts than sharks each year.",
        "The dot over the letters 'i' and 'j' is called a tittle.",
        "A flock of crows is called a murder.",
        "The name 'Wendy' was made up for the book Peter Pan.",
        "The hashtag symbol is technically called an octothorpe.",
        "The plastic tips on shoelaces are called aglets.",
        "Nintendo was founded in 1889 as a playing card company.",
        "The first alarm clock could only ring at 4 AM.",
        "Bubble wrap was originally invented as wallpaper.",
        "A 'butt' is a real unit of measurement (126 gallons of wine).",
        "The average cloud weighs 1.1 million pounds.",
        "Goldfish have a memory span of months, not seconds.",
        "The inventor of the Pez dispenser wanted to help people quit smoking.",
        "Humans are the only animals that blush.",
        "A 'zeptosecond' is one trillionth of a billionth of a second.",
        "Crayola means 'oily chalk' (craie + oleaginous).",
        "The original name for butterfly was 'flutterby'.",
        "A 'contronym' is a word that is its own opposite (like 'cleave').",
        "M&M's stands for Mars and Murrie (the founders).",
        "The first product with a barcode was Wrigley's gum.",
        "A group of unicorns is called a blessing.",
        "The lint in your pocket has a name: gnurr.",
        "Floccinaucinihilipilification is the act of estimating something as worthless.",
        "The smell of rain has a name: petrichor.",
        "Armadillos can walk underwater.",
        "The word 'set' has the most definitions in the English dictionary.",
        "A snail can sleep for 3 years.",
        "Your brain uses 20% of your total oxygen and calorie intake.",
        "The longest English word without a vowel is 'rhythms'.",
        "Pogonophobia is the fear of beards.",
        "A 'jiffy' is an actual unit of time: 1/100th of a second.",
        "Vending machines kill more people than sharks each year.",
        "The King of Hearts is the only king without a mustache.",
        "111,111,111 x 111,111,111 = 12,345,678,987,654,321.",
        "A group of ferrets is called a business.",
        "The longest wedding veil was the length of 63.5 football fields.",
        "Scotland has 421 words for snow.",
        "The opposite of déjà vu is called jamais vu.",
        "Banging your head against a wall burns 150 calories an hour.",
    ],
    "✍️": [  # Writing
        "Stephen King writes 2,000 words every single day, including holidays.",
        "Harry Potter was rejected by 12 publishers before Bloomsbury accepted it.",
        "Ernest Hemingway wrote standing up.",
        "The longest novel ever written is 'In Search of Lost Time' at 1.2 million words.",
        "Dr. Seuss wrote 'Green Eggs and Ham' using only 50 different words on a bet.",
        "Agatha Christie is the best-selling fiction writer of all time (2 billion copies).",
        "Shakespeare invented over 1,700 words including 'assassination' and 'lonely.'",
        "Franz Kafka asked his friend to burn all his writings after death - he didn't.",
        "Maya Angelou rented hotel rooms to write, removing all distractions.",
        "The first novel ever written is considered to be 'The Tale of Genji' (1010 AD).",
        "Mark Twain was the first author to submit a typewritten manuscript.",
        "J.K. Rowling wrote Harry Potter as a single mother on welfare.",
        "Victor Hugo wrote 'Les Misérables' in exile over 17 years.",
        "Edgar Allan Poe was paid $9 for 'The Raven.'",
        "Truman Capote couldn't start or finish writing on a Friday.",
        "The Bible is the most-read book in the world.",
        "George Orwell's real name was Eric Arthur Blair.",
        "Virginia Woolf wrote all her books standing at a desk.",
        "The shortest complete story is 'For sale: baby shoes, never worn.'",
        "Charles Dickens always slept facing north for creativity.",
        "Dan Brown writes hanging upside down in gravity boots to beat writer's block.",
        "Jane Austen published all her books anonymously as 'A Lady.'",
        "Tolstoy's wife copied 'War and Peace' by hand seven times.",
        "Hunter S. Thompson retyped 'The Great Gatsby' to feel the rhythm of great writing.",
        "The Oxford English Dictionary took 70 years to complete.",
        "Ray Bradbury wrote 'Fahrenheit 451' on a coin-operated typewriter in a library basement.",
        "Mary Shelley wrote 'Frankenstein' at age 18.",
        "Roald Dahl wrote in a shed with a sleeping bag and sharpened pencils.",
        "Oscar Wilde wrote 'The Importance of Being Earnest' in three weeks.",
        "The Great Gatsby sold poorly when published and Fitzgerald died thinking it a failure.",
        "Toni Morrison wrote before dawn while her children slept.",
        "Isaac Asimov wrote or edited over 500 books.",
        "The Declaration of Independence was edited by Benjamin Franklin.",
        "Sylvia Plath wrote 'The Bell Jar' under a pseudonym.",
        "The word 'robot' first appeared in a 1920 Czech play by Karel Čapek.",
        "George R.R. Martin writes on DOS using WordStar 4.0.",
        "The Count of Monte Cristo was originally serialized in 18 parts.",
        "Beatrix Potter self-published 'The Tale of Peter Rabbit' after rejections.",
        "Jack Kerouac wrote 'On the Road' on a 120-foot scroll in three weeks.",
        "The first dictionary was published in Mesopotamia around 2300 BC.",
        "Leo Tolstoy was excommunicated by the Russian Orthodox Church.",
        "Haruki Murakami runs 10km daily to maintain writing stamina.",
        "Emily Dickinson published fewer than 12 poems during her lifetime.",
        "The Bronte sisters first published under male pseudonyms.",
        "Anthony Trollope wrote 3,000 words before work every morning.",
        "James Patterson has sold more books than Stephen King and John Grisham combined.",
        "The longest sentence in literature is 13,955 words in 'The Rotter's Club.'",
        "Fyodor Dostoevsky dictated 'The Gambler' in 26 days to pay off debts.",
        "Cormac McCarthy uses no quotation marks in his dialogue.",
        "The pen name 'Mark Twain' means 'two fathoms deep' in riverboat slang.",
    ],
    "🎮": [  # Gaming
        "The PlayStation startup sound was composed to inspire fear and awe.",
        "Minecraft has sold over 300 million copies, making it the best-selling game ever.",
        "The first video game Easter egg was hidden in Atari's Adventure in 1980.",
        "Mario was originally called 'Jumpman' and was a carpenter, not a plumber.",
        "The voice of Mario, Charles Martinet, voiced him for over 30 years.",
        "Tetris was created by a Soviet scientist and caused a legal battle between countries.",
        "The Konami Code (↑↑↓↓←→←→BA) works in over 100 games.",
        "Pac-Man was originally called 'Puck-Man' but changed to avoid vandalism.",
        "World of Warcraft had a plague outbreak that taught epidemiologists about disease spread.",
        "GTA V made $800 million in its first 24 hours - more than any movie ever.",
        "The Legend of Zelda was inspired by creator Miyamoto's childhood exploration.",
        "E.T. for Atari was so bad that unsold copies were buried in a New Mexico desert.",
        "Fortnite made $9 billion in its first two years.",
        "The first gaming console was the Magnavox Odyssey in 1972.",
        "Sonic the Hedgehog was designed to be Sega's answer to Mario.",
        "The longest video game marathon lasted 138 hours playing GTA V.",
        "Donkey Kong was Nintendo's first major hit and introduced Mario.",
        "League of Legends has over 150 million monthly active players.",
        "The Nintendo Switch sold over 140 million units worldwide.",
        "Halo 2 was the first game to popularize online console multiplayer.",
        "Candy Crush makes over $4 million per day from in-app purchases.",
        "The Sims has sold over 200 million copies across all versions.",
        "Speed runners beat Ocarina of Time in under 4 minutes using glitches.",
        "Pong was so simple it had no CPU - just transistors and circuits.",
        "The esports industry is worth over $1.5 billion.",
        "Final Fantasy was named because it was the creator's last chance at success.",
        "The PS2 is the best-selling console ever with 155 million units sold.",
        "Wii Sports is the fourth best-selling game of all time.",
        "Red Dead Redemption 2 cost $540 million to develop.",
        "The Elder Scrolls V: Skyrim has been released on 12+ different platforms.",
        "Nintendo started in 1889 as a playing card company.",
        "The first 3D game was 3D Monster Maze in 1981.",
        "Steam has over 130 million monthly active users.",
        "The Last of Us Part II won 300+ Game of the Year awards.",
        "Roblox has over 70 million daily active users, mostly under 16.",
        "The arcade game industry peaked at $8 billion in 1982.",
        "Doom popularized the first-person shooter genre in 1993.",
        "The Game Boy's green screen was chosen to save battery life.",
        "Animal Crossing: New Horizons sold 13 million copies in 6 weeks.",
        "The first video game tournament was for Spacewar! at Stanford in 1972.",
        "Call of Duty: Modern Warfare 2 made $550 million in 3 days.",
        "Pokémon is the highest-grossing media franchise of all time.",
        "Cyberpunk 2077 had 8 million pre-orders despite its buggy launch.",
        "The Witcher 3 has 16 free DLCs and 2 massive paid expansions.",
        "Atari buried millions of unsold cartridges in 1983 (confirmed in 2014).",
        "Elden Ring sold 12 million copies in 3 weeks.",
        "The first mobile game was Tetris on the Hagenuk MT-2000 in 1994.",
        "Twitch streamers can earn millions per year from subscriptions and donations.",
        "Nintendo's Shigeru Miyamoto created Mario, Zelda, and Donkey Kong.",
        "The PS5 and Xbox Series X both use custom AMD chips.",
    ],
    "✈️": [  # Travel
        "Singapore Changi Airport has a butterfly garden, rooftop pool, and movie theater.",
        "The longest flight in the world is Singapore to New York at 18+ hours.",
        "Iceland's Keflavik Airport has a duty-free store inside a lava cave replica.",
        "Japan's trains are so punctual that delays of 5+ minutes come with apology certificates.",
        "Venice is sinking at a rate of 1-2 millimeters per year.",
        "The Great Wall of China is not a single wall but a series of walls and fortifications.",
        "Dubai's Palm Jumeirah added 78 kilometers of coastline to the city.",
        "Norway has 'slow TV' - hours of train journeys broadcast in real-time.",
        "Bhutan measures success by Gross National Happiness, not GDP.",
        "The Trans-Siberian Railway spans 9,289 km across 7 time zones.",
        "Monaco is smaller than Central Park in New York City.",
        "The Maldives is the lowest country in the world, averaging 1.5m above sea level.",
        "There are more than 7,000 islands in the Philippines.",
        "Switzerland has enough nuclear bunkers to shelter its entire population.",
        "The shortest commercial flight is 57 seconds between two Scottish islands.",
        "Machu Picchu was unknown to the outside world until 1911.",
        "Singapore has laws against chewing gum to keep the city clean.",
        "The Eiffel Tower was supposed to be temporary and demolished after 20 years.",
        "Antarctica is the only continent with no permanent human population.",
        "Greenland is the world's largest island that isn't a continent.",
        "The Vatican City is the smallest country in the world at 0.17 square miles.",
        "Tokyo's Shibuya Crossing sees 3,000 people cross at once during peak times.",
        "The Amazon River doesn't have a single bridge crossing it.",
        "New Zealand was the first country to give women the right to vote.",
        "The Dead Sea is Earth's lowest point on land at 430m below sea level.",
        "Finland has more saunas than cars.",
        "The Burj Khalifa is so tall you can watch the sunset twice from different floors.",
        "Prague's astronomical clock has been operating since 1410.",
        "Australia's Great Ocean Road is the world's largest war memorial.",
        "There are 6 countries you can fly to that have no airports.",
        "The Galápagos Islands inspired Darwin's theory of evolution.",
        "Iceland has no mosquitoes.",
        "South Africa has three capital cities - Pretoria, Cape Town, and Bloemfontein.",
        "The Mariana Trench is deeper than Mount Everest is tall.",
        "Japan has over 6,800 islands.",
        "The shortest international bridge connects Portugal and Spain (3.2 meters).",
        "Liechtenstein and Uzbekistan are the only doubly landlocked countries.",
        "The Colosseum could seat 50,000 spectators.",
        "Canada has the longest coastline in the world at 202,080 km.",
        "The Northern Lights are visible from over 60 countries.",
        "Easter Island is one of the most remote inhabited places on Earth.",
        "The Louvre receives more visitors than any other museum (10 million/year).",
        "Singapore is one of only three city-states in the world.",
        "The Sahara Desert is almost the same size as the United States.",
        "Dutch people are the tallest in the world on average.",
        "Ethiopia follows a calendar that is 7 years behind the rest of the world.",
        "The oldest hotel in the world is in Japan, operating since 705 AD.",
        "There are more than 200 bodies still on Mount Everest.",
        "Palau requires tourists to sign an eco-pledge stamped in their passport.",
        "The International Date Line zigzags to keep island nations in the same day.",
    ],
    "🎨": [  # Art
        "The Mona Lisa has no eyebrows - it was fashionable to shave them in Renaissance Florence.",
        "Van Gogh only sold one painting during his lifetime.",
        "Picasso could draw before he could walk and his first word was 'pencil.'",
        "The Scream was painted on cardboard, not canvas.",
        "Michelangelo painted the Sistine Chapel ceiling standing up, not lying down.",
        "Banksy shredded his own painting moments after it sold for $1.4 million.",
        "The Mona Lisa was stolen in 1911 and missing for 2 years.",
        "Monet's water lilies span over 250 paintings created over 30 years.",
        "Frida Kahlo started painting after a bus accident left her bedridden.",
        "Da Vinci wrote backwards so his notes could only be read in a mirror.",
        "Starry Night was painted from Van Gogh's asylum room window.",
        "The Girl with a Pearl Earring is called the 'Mona Lisa of the North.'",
        "Salvador Dalí designed the Chupa Chups lollipop logo.",
        "Rembrandt painted over 90 self-portraits throughout his career.",
        "The Louvre would take 200 days to view every piece for 30 seconds each.",
        "Jackson Pollock's drip paintings revolutionized abstract expressionism.",
        "Vermeer only completed about 35 paintings in his entire lifetime.",
        "The ceiling of the Sistine Chapel took Michelangelo 4 years to complete.",
        "Claude Monet's cataracts influenced his later, more abstract style.",
        "Andy Warhol's Campbell's Soup Cans series has 32 paintings, one for each flavor.",
        "The Terracotta Army has 8,000 soldiers and no two faces are alike.",
        "Basquiat went from homeless graffiti artist to selling paintings for millions.",
        "The persistence of memory's melting clocks were inspired by melting cheese.",
        "Georgia O'Keeffe is known as the 'Mother of American Modernism.'",
        "Hokusai's Great Wave is one of the most reproduced images in history.",
        "The Venus de Milo's missing arms were never found.",
        "Henri Matisse cut paper shapes with scissors when he could no longer paint.",
        "The Thinker was originally part of a larger sculpture called The Gates of Hell.",
        "Yayoi Kusama has lived voluntarily in a psychiatric hospital since 1977.",
        "Bob Ross painted over 30,000 paintings and gave most away for free.",
        "The Night Watch was trimmed to fit between two doors, cutting off figures.",
        "Rothko's color field paintings are meant to evoke deep emotional responses.",
        "Caravaggio killed a man and spent his final years fleeing murder charges.",
        "The David statue is 17 feet tall and weighs over 12,000 pounds.",
        "Impressionism was named as an insult by a critic mocking Monet's style.",
        "Keith Haring started as a subway graffiti artist in New York.",
        "The oldest known cave paintings are over 45,000 years old.",
        "Artemisia Gentileschi was one of the first female artists to gain recognition.",
        "Duchamp's urinal ('Fountain') changed the definition of art forever.",
        "Goya's 'Black Paintings' were never meant to be seen by the public.",
        "Jean-Michel Basquiat died at 27, the same age as many rock legends.",
        "The Arnolfini Portrait may be the first known selfie - Van Eyck is in the mirror.",
        "Kintsugi is the Japanese art of repairing broken pottery with gold.",
        "Banksy's identity remains unknown despite being world famous.",
        "Norman Rockwell painted 323 covers for The Saturday Evening Post.",
        "The Birth of Venus was nearly destroyed by Savonarola's 'Bonfire of the Vanities.'",
        "Warhol's studio was called 'The Factory' and operated like an assembly line.",
        "Edvard Munch created 4 versions of The Scream in different media.",
        "The Guernica by Picasso depicts the Nazi bombing of a Spanish town.",
        "A Pollock painting sold for $200 million, one of the highest prices ever.",
    ],
    "⚡": [  # Famous Inventors
        "Nikola Tesla envisioned smartphones in 1926, calling them 'wireless communication.'",
        "Thomas Edison held 1,093 patents - the most by any individual in US history.",
        "The Wright Brothers' first flight was shorter than a Boeing 747's wingspan.",
        "Marie Curie is the only person to win Nobel Prizes in two different sciences.",
        "Alexander Graham Bell considered the telephone an intrusion and refused to have one in his study.",
        "Leonardo da Vinci designed a helicopter 400 years before one was built.",
        "Tim Berners-Lee invented the World Wide Web and gave it away for free.",
        "Hedy Lamarr, the actress, co-invented frequency hopping that led to WiFi and Bluetooth.",
        "Benjamin Franklin never patented any of his inventions, including bifocals.",
        "Eli Whitney's cotton gin made slavery more profitable, the opposite of his intention.",
        "James Watt didn't invent the steam engine - he dramatically improved it.",
        "Philo Farnsworth invented television at age 21 but died in obscurity.",
        "George Washington Carver developed 300+ products from peanuts.",
        "Stephanie Kwolek invented Kevlar, which is 5x stronger than steel.",
        "Percy Spencer discovered microwaves cook food when a chocolate bar melted in his pocket.",
        "Charles Babbage designed the first computer in the 1830s but never completed it.",
        "Johannes Gutenberg died bankrupt despite inventing the printing press.",
        "Alfred Nobel invented dynamite and created the Nobel Prize to improve his legacy.",
        "Alexander Fleming discovered penicillin by accident from mold contamination.",
        "Grace Hopper invented the first compiler and popularized the term 'debugging.'",
        "Garrett Morgan invented the traffic light and the gas mask.",
        "Ruth Handler created Barbie, named after her daughter Barbara.",
        "Willis Carrier invented air conditioning to control humidity in a printing plant.",
        "John Logie Baird gave the first TV demonstration using a ventriloquist dummy.",
        "Louis Pasteur's vaccines were tested on humans before animal trials.",
        "The inventor of the Segway died riding a Segway off a cliff.",
        "Steve Wozniak built the first Apple computer and sold it for $666.66.",
        "James Dyson created 5,127 failed prototypes before his bagless vacuum worked.",
        "Clarence Birdseye invented flash freezing after seeing Inuit freeze fish instantly.",
        "Mary Anderson invented windshield wipers after a NYC trolley ride in the rain.",
        "Samuel Morse was a famous portrait painter before inventing the telegraph.",
        "Lonnie Johnson, a NASA engineer, invented the Super Soaker water gun.",
        "George Eastman made photography accessible with the Kodak camera in 1888.",
        "Nikola Tesla died penniless in a hotel room despite his revolutionary inventions.",
        "Robert Jarvik didn't invent the artificial heart - he improved an existing design.",
        "Ada Lovelace wrote the first computer algorithm in 1843.",
        "Jack Kilby invented the integrated circuit and won the Nobel Prize at age 77.",
        "Lise Meitner discovered nuclear fission but was denied the Nobel Prize.",
        "Dean Kamen invented the insulin pump, portable dialysis, and the Segway.",
        "Tim Berners-Lee's first web page is still online at info.cern.ch.",
        "Ralph Baer invented the first home video game console, the Magnavox Odyssey.",
        "Josephine Cochrane invented the dishwasher because servants chipped her china.",
        "Igor Sikorsky built the first successful helicopter after failures in Russia.",
        "John Harrison solved the longitude problem with his marine chronometer.",
        "Katherine Johnson's calculations sent astronauts to the Moon.",
        "Vint Cerf and Bob Kahn invented TCP/IP, the backbone of the internet.",
        "Chester Carlson invented xerography (photocopying) after 20+ companies rejected it.",
        "Elon Musk didn't found Tesla - he was an early investor who became CEO.",
        "Alan Turing's work at Bletchley Park shortened WWII by an estimated 2 years.",
        "Margaret Knight invented the flat-bottomed paper bag and held 27 patents.",
    ],
    "🔢": [  # Math & Science
        "Pi has been calculated to over 100 trillion digits.",
        "Zero was invented independently by the Babylonians, Mayans, and Indians.",
        "A googol is 10^100; a googolplex is 10^googol.",
        "The Fibonacci sequence appears in sunflower seeds, pinecones, and galaxies.",
        "Euler's identity (e^(iπ) + 1 = 0) is called the most beautiful equation in math.",
        "There are more ways to shuffle a deck of cards than atoms on Earth.",
        "The square root of 2 was the first known irrational number.",
        "Prime numbers are the building blocks of all other numbers.",
        "The Riemann Hypothesis, unsolved since 1859, has a $1M prize.",
        "Infinity comes in different sizes - some infinities are bigger than others.",
        "The Pythagorean theorem was known 1,000 years before Pythagoras.",
        "E=mc² means a paperclip contains enough energy to power a city.",
        "Schrödinger's cat thought experiment shows quantum superposition absurdity.",
        "The double-slit experiment proves light behaves as both wave and particle.",
        "CRISPR allows scientists to edit genes like cutting and pasting text.",
        "DNA was discovered in 1869, but its structure wasn't known until 1953.",
        "The human genome has about 3 billion base pairs.",
        "Mitochondria have their own DNA, inherited only from your mother.",
        "Penicillin was discovered by accident when mold contaminated a petri dish.",
        "The placebo effect works even when patients know it's a placebo.",
        "Banach-Tarski paradox: you can split a sphere into 5 pieces and reassemble into 2 spheres.",
        "Gödel's incompleteness theorems prove math can never be complete and consistent.",
        "The sum of all positive integers (1+2+3+...) equals -1/12 in some contexts.",
        "P vs NP is the biggest unsolved problem in computer science ($1M prize).",
        "The golden ratio (1.618...) appears in art, architecture, and nature.",
        "A Möbius strip has only one side and one edge.",
        "The four color theorem says any map needs only 4 colors so no regions touch.",
        "Fermat's Last Theorem took 358 years to prove.",
        "The butterfly effect: tiny changes can lead to vastly different outcomes.",
        "Entropy always increases - the universe trends toward disorder.",
        "Black holes emit Hawking radiation and slowly evaporate.",
        "Heisenberg's uncertainty principle: you can't know both position and momentum exactly.",
        "LIGO detected gravitational waves from colliding black holes 1.3B light-years away.",
        "Absolute zero (0 Kelvin) is impossible to reach but can be approached.",
        "The half-life of carbon-14 is 5,730 years, useful for dating ancient objects.",
        "Avogadro's number (6.022×10²³) is the number of atoms in 12g of carbon.",
        "The speed of light in a vacuum is exactly 299,792,458 m/s by definition.",
        "Quarks come in 6 flavors: up, down, charm, strange, top, bottom.",
        "The Higgs boson gives other particles mass and was confirmed in 2012.",
        "String theory proposes 10 or 11 dimensions, most too small to observe.",
        "The Mandelbrot set is infinitely complex at every scale.",
        "Chaos theory studies systems sensitive to initial conditions.",
        "There are 10^80 atoms in the observable universe.",
        "Graham's number is so large that the observable universe can't contain its digits.",
        "The twin prime conjecture (primes like 11,13 or 17,19) remains unproven.",
        "Imaginary numbers (√-1 = i) are essential for quantum mechanics.",
        "The Monty Hall problem shows switching doors gives 2/3 chance of winning.",
        "Bayes' theorem revolutionized probability and powers modern AI.",
        "The three-body problem has no general closed-form solution.",
        "Game theory's Nash equilibrium won John Nash the Nobel Prize.",
    ],
    "🎬": [  # Movies, Music & Quotes
        "The Shawshank Redemption was a box office flop but became the top-rated film on IMDb.",
        "The Lion King's 'Hakuna Matata' means 'no worries' in Swahili.",
        "Beethoven composed his greatest works while completely deaf.",
        "'Here's looking at you, kid' from Casablanca was improvised by Humphrey Bogart.",
        "The Dark Side of the Moon by Pink Floyd spent 937 weeks on the Billboard 200.",
        "Stanley Kubrick made The Shining's crew build the hotel set from scratch.",
        "'May the Force be with you' was voted the most iconic movie line ever.",
        "Mozart composed over 600 works before dying at age 35.",
        "The Godfather's cat was a stray Marlon Brando found on the studio lot.",
        "'I'll be back' - Schwarzenegger wanted to say 'I will be back' but Cameron refused.",
        "Bohemian Rhapsody was considered too long for radio at 6 minutes.",
        "Inception's ending was left ambiguous - Nolan never confirmed if it's a dream.",
        "'To infinity and beyond!' was almost 'To infinity and beyond... and back!'",
        "The Beatles hold the record for most #1 hits on the Billboard Hot 100 (20).",
        "Jaws made people so afraid of sharks that beach attendance dropped 50%.",
        "'Life is like a box of chocolates' - the book version says 'life is A box of chocolates.'",
        "Michael Jackson's Thriller is the best-selling album of all time (70M+ copies).",
        "The Wizard of Oz's ruby slippers were silver in the book.",
        "'You can't handle the truth!' was improvised by Jack Nicholson.",
        "Freddie Mercury had four extra teeth, giving him his distinctive voice.",
        "Fight Club's first rule being broken constantly is the point of the satire.",
        "'Houston, we have a problem' - the actual quote was 'Houston, we've had a problem.'",
        "Elvis Presley never performed outside North America.",
        "The Matrix's green code is actually sushi recipes.",
        "'Be the change you wish to see in the world' - Gandhi never actually said this.",
        "The Lord of the Rings trilogy was filmed simultaneously over 438 days.",
        "Bob Dylan won the Nobel Prize in Literature in 2016.",
        "'Elementary, my dear Watson' never appears in the original Sherlock Holmes books.",
        "Titanic's 'I'm the king of the world!' was improvised by Leonardo DiCaprio.",
        "Queen's 'We Will Rock You' stomp-stomp-clap was designed for stadium singalongs.",
        "The Godfather Part II is one of few sequels to win Best Picture.",
        "'Play it again, Sam' - Humphrey Bogart never said this in Casablanca.",
        "Prince changed his name to a symbol to escape his record contract.",
        "Pulp Fiction's dance scene was inspired by 8½ by Federico Fellini.",
        "'I see dead people' was ranked the #1 movie spoiler of all time.",
        "The Rolling Stones are still touring after 60+ years together.",
        "2001: A Space Odyssey has only 40 minutes of dialogue in 2.5 hours.",
        "'Frankly, my dear, I don't give a damn' was scandalous for using 'damn' in 1939.",
        "David Bowie invented the persona Ziggy Stardust and 'killed' him on stage.",
        "Citizen Kane's 'Rosebud' sled was burned for the film - only 3 prop sleds exist.",
        "'The only thing we have to fear is fear itself' - FDR's 1933 inaugural address.",
        "Led Zeppelin's 'Stairway to Heaven' has never been released as a single.",
        "Psycho was the first American film to show a toilet flushing.",
        "'I have a dream' - MLK improvised much of the famous speech.",
        "Nirvana's 'Smells Like Teen Spirit' was named after a deodorant brand.",
        "Blade Runner flopped in 1982 but is now considered one of the greatest sci-fi films.",
        "'That's one small step for man' - Armstrong claims he said 'a man' but audio is unclear.",
        "The Silence of the Lambs won all five major Oscars (Best Picture, Director, Actor, Actress, Screenplay).",
        "Bob Marley's last words were 'Money can't buy life.'",
        "'Why so serious?' - Heath Ledger's Joker performance was completed before his death.",
    ],
    "💪": [  # Health & Wellness
        "HRV (heart rate variability) is one of the best indicators of overall health and recovery.",
        "Higher HRV generally indicates better cardiovascular fitness and stress resilience.",
        "Bryan Johnson spends $2+ million per year on his Blueprint longevity protocol.",
        "Bryan Johnson claims to have the heart of a 37-year-old and lungs of an 18-year-old.",
        "Andrew Huberman recommends getting sunlight in your eyes within 30 minutes of waking.",
        "Creatine is one of the most studied and effective supplements for muscle and brain.",
        "Creatine monohydrate (3-5g daily) can improve cognitive function and memory.",
        "Sleep score is calculated from duration, efficiency, restfulness, and sleep stages.",
        "Deep sleep is when your body releases growth hormone and repairs tissues.",
        "REM sleep is critical for memory consolidation and emotional processing.",
        "The ideal room temperature for sleep is 65-68°F (18-20°C).",
        "Huberman suggests viewing morning sunlight for 10+ minutes to set your circadian rhythm.",
        "Bryan Johnson goes to bed at the same time every night and tracks 100+ biomarkers.",
        "Zone 2 cardio (conversational pace) builds mitochondrial density and fat oxidation.",
        "VO2 max is the strongest predictor of longevity according to Peter Attia.",
        "Cold exposure can increase dopamine by 250% for several hours.",
        "Huberman recommends 1-3 minute cold showers at the end for dopamine and alertness.",
        "Bryan Johnson's Blueprint includes 100+ supplements and strict meal timing.",
        "Magnesium threonate can improve sleep quality and cognitive function.",
        "The glymphatic system clears brain toxins during deep sleep.",
        "Mouth taping during sleep can improve sleep quality by promoting nasal breathing.",
        "HRV is best measured first thing in the morning before getting out of bed.",
        "WHOOP, Oura Ring, and Apple Watch all track HRV and sleep metrics.",
        "Alcohol significantly reduces REM sleep and HRV even in small amounts.",
        "Huberman's 'NSDR' (non-sleep deep rest) can restore dopamine and focus.",
        "Bryan Johnson reversed his epigenetic age by 5+ years according to tests.",
        "Creatine can help with depression and is being studied for mental health.",
        "Sleep consistency (same bed/wake time) matters more than total sleep duration.",
        "Peter Attia calls exercise the most powerful longevity drug we have.",
        "Resistance training 2-3x per week reduces all-cause mortality significantly.",
        "Omega-3 fatty acids (EPA/DHA) reduce inflammation and support brain health.",
        "Vitamin D deficiency is linked to poor immune function and mood disorders.",
        "Huberman suggests delaying caffeine 90-120 minutes after waking for better energy.",
        "Sauna use 4-7x per week reduces cardiovascular mortality by 50%.",
        "Bryan Johnson eats his last meal at 11am and practices strict time-restricted eating.",
        "HRV training with biofeedback can improve stress resilience over time.",
        "The '10,000 steps' goal was a marketing campaign, but walking is still excellent.",
        "Resting heart rate decreases as cardiovascular fitness improves.",
        "Continuous glucose monitors (CGMs) help identify foods that spike blood sugar.",
        "Huberman recommends keeping phones out of the bedroom for better sleep.",
        "Bryan Johnson's team includes 30+ doctors and researchers.",
        "Sleep deprivation impairs insulin sensitivity similar to type 2 diabetes.",
        "Ashwagandha can reduce cortisol levels by 23% in stressed adults.",
        "L-theanine (found in green tea) promotes calm focus without drowsiness.",
        "Rapamycin is being studied as a potential longevity drug.",
        "Metformin is used off-label by some for its potential anti-aging effects.",
        "NAD+ levels decline with age; NMN and NR supplements aim to restore them.",
        "Huberman's toolkit includes sunlight, exercise, cold, heat, and breath work.",
        "Bryan Johnson measures his 'speed of aging' and aims for 0.69 (aging slower).",
        "The 4 pillars of longevity: sleep, nutrition, exercise, and stress management.",
    ],
    "🦄": [  # Startups
        "The term 'unicorn' was coined in 2013 for startups valued over $1 billion.",
        "Airbnb started when founders rented air mattresses in their apartment.",
        "WhatsApp was rejected by Facebook and Twitter before being acquired for $19B.",
        "Slack started as an internal tool for a failed video game company.",
        "YouTube's first video was uploaded from the San Diego Zoo in 2005.",
        "The first version of Facebook was called TheFacebook.",
        "Dropbox's MVP was just a demo video - no working product.",
        "Instagram had only 13 employees when Facebook bought it for $1 billion.",
        "Stripe's founders were in their early 20s when they started.",
        "Uber was originally called UberCab.",
        "Pinterest was originally called Tote and was a mobile shopping app.",
        "Netflix started as a DVD-by-mail rental service.",
        "Twitter was born from a failed podcast platform called Odeo.",
        "The first Amazon logo showed the A to Z arrow like today.",
        "LinkedIn launched in founder Reid Hoffman's living room in 2003.",
        "Spotify launched in 2008 with only 1 million songs.",
        "Square was founded because Jim McKelvey lost a sale due to payment issues.",
        "Zoom's founder was rejected for a US visa 8 times before starting the company.",
        "The term 'pivot' was popularized by Eric Ries in 'The Lean Startup'.",
        "Y Combinator has funded over 4,000 companies including Airbnb and Stripe.",
        "GitHub was bootstrapped for 3 years before taking VC funding.",
        "Shopify started as an online snowboard shop.",
        "Canva was rejected by over 100 investors before raising funds.",
        "DoorDash founders delivered food themselves in the early days.",
        "Notion's founders rebuilt the product from scratch twice before success.",
        "PayPal's original business was cryptography for PDAs.",
        "The 'PayPal Mafia' founded YouTube, LinkedIn, Tesla, and many others.",
        "SpaceX nearly went bankrupt after three failed rocket launches.",
        "Twitch was originally called Justin.tv and showed one person's life 24/7.",
        "Coinbase started in a two-bedroom apartment in San Francisco.",
        "Figma was in development for 4 years before launching.",
        "Discord was originally built for gamers but expanded to communities.",
        "Robinhood launched with a waitlist of 1 million people.",
        "Snapchat's disappearing messages were inspired by real-life conversations.",
        "TikTok's parent company ByteDance is the most valuable startup ever.",
        "Reddit's founders posted fake content to make the site look active.",
        "Atlassian bootstrapped to a $10B+ valuation without VC funding initially.",
        "Calendly was built because the founder hated scheduling meetings.",
        "Warby Parker started because glasses were too expensive.",
        "Airbnb sold cereal boxes ('Obama O's') to fund their startup.",
        "Tesla's first car, the Roadster, was based on a Lotus Elise.",
        "Instacart was founded during Y Combinator's 2012 summer batch.",
        "Zendesk started in Copenhagen before moving to San Francisco.",
        "Peloton raised over $1B before going public in 2019.",
        "The 'Series A crunch' refers to the difficulty raising after seed funding.",
        "Quora was founded by former Facebook employees.",
        "GitLab was fully remote from day one with no office.",
        "Bird scooters raised $300 million in just 14 months.",
        "WeWork was valued at $47B before its valuation collapsed.",
        "OpenAI started as a non-profit before creating a capped-profit entity.",
    ],
}

# ANSI color codes
CYAN = "\033[36m"
YELLOW = "\033[33m"
MAGENTA = "\033[35m"
RESET = "\033[0m"
BOLD = "\033[1m"
DIM = "\033[2m"

def get_random_fact():
    """Get a random fact with its category emoji, seeded by current second to change periodically"""
    # Change fact every 5 seconds
    seed = int(time.time() / 5)
    random.seed(seed)

    # Flatten all facts into a list with their emoji
    all_facts = [(emoji, fact) for emoji, facts in FACTS.items() for fact in facts]

    return random.choice(all_facts)

def main():
    try:
        # Read JSON input from Claude Code
        input_data = sys.stdin.read()
        data = json.loads(input_data) if input_data.strip() else {}

        # Get session info
        model = data.get("model", "claude")
        cost = data.get("cost", {})
        total_cost = cost.get("total", 0) if isinstance(cost, dict) else 0

        # Get a random fact with its emoji
        emoji, fact = get_random_fact()

        # Truncate fact if too long for terminal
        max_fact_len = 75  # Reduced to account for emoji
        if len(fact) > max_fact_len:
            fact = fact[:max_fact_len-3] + "..."

        # Build status line with category emoji
        status = f"{emoji} {CYAN}{BOLD}Did you know?{RESET} {DIM}{fact}{RESET}"

        print(status)

    except Exception as e:
        # Fallback if something goes wrong
        print(f"{CYAN}Thinking...{RESET}")

if __name__ == "__main__":
    main()
